In [6]:
import pandas as pd
import glob
import json

In [ ]:

#all_sec = glob.glob('loaded/poincare_sections/sect_5*.csv')

#trajs = pd.concat([pd.read_csv(file) for file in all_traj], ignore_index=True)
#secs = pd.concat([pd.read_csv(file) for file in all_sec], ignore_index=True)

In [ ]:
import json
import glob
import pandas as pd

all_traj = glob.glob('loaded/trajectories/traj_5_*.csv')

orb_parts = []
trajectory_parts = []

for file in all_traj:
    traj = pd.read_csv(file)
    
    orb_parts.append(traj[["orbit_id", "x", "y", "z", "vx", "vy", "vz"]])
    
    for idx, row in traj.iterrows():
        orbit_id = row['orbit_id']
        points = json.loads(row['v'])
        
        for point in points:
            point['orbit_id'] = orbit_id
            trajectory_parts.append(point)

# Объединяем результаты
orb = pd.concat(orb_parts, ignore_index=True)
trajectory = pd.DataFrame(trajectory_parts)

# Упорядочиваем колонки
trajectory = trajectory[['orbit_id', 't', 'x', 'y', 'z', 'vx', 'vy', 'vz']]

In [10]:
orb

      orbit_id              x    y             z   vx        vy   vz
0        19507  331156.058063  0.0  17997.152005  0.0 -0.146188  0.0
1        19508  363708.867816  0.0  38641.731048  0.0 -0.374197  0.0
2        19509  333998.483518  0.0  45399.114844  0.0 -0.046056  0.0
3        19510  363623.863250  0.0  36873.102669  0.0 -0.387823  0.0
4        19511  328732.783648  0.0  71736.547356  0.0  0.225733  0.0
...        ...            ...  ...           ...  ...       ...  ...
1131     18555  351892.305490  0.0  71797.722802  0.0 -0.106275  0.0
1132     18556  317273.734639  0.0  36937.258721  0.0  0.236842  0.0
1133     18557  319443.883281  0.0  55898.680732  0.0  0.317906  0.0
1134     18558  316764.721218  0.0  35724.006789  0.0  0.242888  0.0
1135     18559  352471.489944  0.0  71133.263671  0.0 -0.113768  0.0

[1136 rows x 7 columns]

In [10]:
sec_df = pd.read_csv("loaded/poincare_sections/sect_2_new.csv")

In [11]:
sec_df

       orbit_id   plane                                                  v
0         12332  vz = 0  [{"t":5.8262524689,"x":316053.5963914527,"y":-...
1         12332  vx = 0  [{"t":0.7112878707,"x":0,"y":-21376.5959359894...
2         12332  vy = 0  [{"t":3.0365644435,"x":337317.3549388139,"y":0...
3         12332   y = 0  [{"t":6.4984904067,"x":314776.456892505,"y":-0...
4         12332   z = 0  [{"t":0,"x":344458.2087209069,"y":-46898.75857...
...         ...     ...                                                ...
21095     24600   y = 0  [{"t":5.7969176306,"x":335466.2166294572,"y":-...
21096     24600   z = 0  [{"t":0,"x":327953.6002125412,"y":19873.860525...
21097     24600  vx = 0  [{"t":6.1137704969,"x":0,"y":-4006.5455562962,...
21098     24600  vy = 0  [{"t":3.1608315998,"x":327126.8119580204,"y":0...
21099     24600  vz = 0  [{"t":6.2318402748,"x":335611.146062894,"y":-5...

[21100 rows x 3 columns]

In [12]:
sec_parts = []
for _, row in sec_df.iterrows():
        orbit_id = row["orbit_id"]
        plane = row["plane"]
        points = json.loads(row["v"])
        for point in points:
            point["orbit_id"] = orbit_id
            point["plane"] = plane
            sec_parts.append(point)

secs = pd.DataFrame(sec_parts)
secs = secs[["orbit_id", "plane", "t", "x", "y", "z", "vx", "vy", "vz"]]
secs

,orbit_id,plane,t,x,y,z,vx,vy,vz
0,12332,vz = 0,5.826252,316053.596391,-15954.816950,0.0,-0.041380,0.264956,-9.547630e-18
1,12332,vz = 0,12.209983,348524.789596,16505.022750,0.0,-0.015405,-0.297478,-0.000000e+00
2,12332,vz = 0,18.101273,322567.275016,-18246.429338,0.0,-0.044317,0.188283,-1.425483e-16
3,12332,vz = 0,24.598961,347947.157121,6541.468462,0.0,-0.001072,-0.247605,8.393033e-17
4,12332,vz = 0,30.898289,324082.930815,4625.937706,0.0,0.011053,0.170148,8.287565e-17
...,...,...,...,...,...,...,...,...,...
1934501,24600,vz = 0,520.788530,315306.658370,21673.870591,0.0,0.055524,0.210818,-0.000000e+00
1934502,24600,vz = 0,526.496136,337468.478538,-10772.696663,0.0,0.005749,-0.267203,-2.864289e-16
1934503,24600,vz = 0,532.494659,312591.123138,2727.546239,0.0,0.007258,0.246960,-7.378597e-17
1934504,24600,vz = 0,538.408586,337392.915240,6793.878015,0.0,-0.004367,-0.275079,4.311837e-16
1934505,24600,vz = 0,544.139530,314424.808988,-18079.233700,0.0,-0.046902,0.222534,2.418548e-16